Namespace: GLib
Version: 2.0
CIncludes:
    - "glib-object.h"
    - "glib-unix.h"
    - "glib/gstdio.h"
FunctionBlacklist:
    - "g_date_to_struct_tm"
    - "g_assert_warning"
    - "g_atexit"
    - "g_variant_parser_get_error_quark"
    - "g_variant_get_gtype"
    - "g_trash_stack_push"
    - "g_trash_stack_peek"
    - "g_trash_stack_pop"
    - "g_trash_stack_height"
    - "g_test_trap_fork"
    - "g_unicode_canonical_decomposition"
    - "g_atomic_int_inc"
    - "g_atomic_int_add"
    - "g_atomic_int_and"
    - "g_atomic_int_or"
    - "g_atomic_int_xor"
    - "g_atomic_int_dec_and_test"
    - "g_atomic_int_compare_and_exchange"
    - "g_atomic_int_exchange_and_add"
    - "g_atomic_int_get"
    - "g_atomic_int_set"
    - "g_atomic_pointer_add"
    - "g_atomic_pointer_and"
    - "g_atomic_pointer_get"
    - "g_atomic_pointer_set"
    - "g_atomic_pointer_xor"
    - "g_atomic_pointer_or"
    - "g_atomic_pointer_compare_and_exchange"
    - "g_basename"
    - "g_strncasecmp"
    - "g_strup"
    - "g_string_up"
    - "g_string_down"
    - "g_strdown"
    - "g_strcasecmp"
    - "g_source_get_current_time"
    - "g_slice_set_config"
    - "g_slice_get_config_state"
    - "g_slice_get_config"
    - "g_date_set_time"
    - "g_format_size_for_display"
    - "g_io_channel_close"
    - "g_io_channel_seek"
    - "g_io_channel_write"
    - "g_io_channel_read"
    - "g_mem_is_system_malloc"
    - "g_mapped_file_free"
    - "g_mem_profile"
    - "g_mem_set_vtable"
    - "g_once_init_enter"
    - "g_once_init_leave"
    - "g_option_group_free"
    - "g_pointer_bit_lock"
    - "g_pointer_bit_trylock"
    - "g_pointer_bit_unlock"
    - "g_strv_get_type"
    - "g_bytes_compare"
    - "g_bytes_equal"
    - "g_bytes_hash"
    - "g_variant_compare"
    - "g_variant_equal"
    - "g_variant_hash"
    - "g_variant_type_equal"
    - "g_variant_type_hash"
    - "g_file_test"
    - "g_source_remove"
    - "g_option_group_set_translate_func"
    - "g_test_add_data_func_full"
    - "g_async_queue_ref_unlocked" #d
    - "g_async_queue_unref_and_unlock" #d
    - "g_async_queue_timed_pop" #d
    - "g_async_queue_timed_pop_unlocked" #d
    - "g_iconv"
    - "g_iconv_close"
RecordBlacklist:
    - "TestLogMsg"
ConstantRename:
    CSET_a_2_z: "Cseta2z"
